### ISSUE TITLE
Cannot export database to a file

### ISSUE THREAD

**Issue by Omicron166** [jakobkreft/LabLog#3]
**Describe the bug**
When I try to export the database to a file I get the "Permission required to export data" toast.
I tried to allow the permission from android settings but the only thing available is allow access to camera.
I use the 1.5 build from f-droid. 

**To Reproduce**
1. Create a test entry to have something to export
2. Don't connect to a mqtt broker
3. Go to settings -> Import/Export Database
4. Click on export

**Smartphone:**
 - Device: Huawei P smart 2019
 - OS: Android 10

**Comment by jakobkreft** [comment]
Thanks! I think I know the root cause of the issue on Android 10 (API 29), so I will be able to fix it in the next version.

**Comment by jakobkreft** [comment]
I have fixed the issue in the latest release v1.6 now available on Github. New version will be available on F-droid in a week. Please let me know if this fixed the issue for you!

**Comment by Omicron166** [comment]
The issue is fixed.
