### ISSUE TITLE
Importing pictures

### ISSUE THREAD

**Issue by testcocoon** [jakobkreft/LabLog#4]
Adding a photo into the log is nice, but it would be convenient to pick also a picture from a gallery.

**Comment by jakobkreft** [comment]
Indeed that would be useful! Thanks for the feedback!

**Comment by jakobkreft** [comment]
@testcocoon I have added this feature in the new release v1.7. You can expect the update available also on F-droid in about a week. Let me know if you encounter any problems! Thanks.
